server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
#          uri: file:///Users/kimjisu/Desktop/Intellij/inflearn/cloud-config
          uri: https://github.com/jisu3316/spring-cloud-config.git

management:
  endpoints:
    web:
      exposure:
        include: health, busrefresh